#!/usr/bin/perl

=head1 NAME

Mnet::script::Mnet-object-info - network automation script

=cut

# Copyright 2006, 2013-2014 Michael J. Menza Jr.
# Refer to `perldoc Mnet` for more information.

=head1 SYNOPSIS

Usage examples:

 Mnet-object-info \
    --db-name mnet.db \
    --data-dir /data/dir \
    --object-name localhost

=head1 DESCRIPTION

This script uses the Mnet::Model module to output a dump of data on
the object-name specified on the command line.

Wildcards cannot be used in the --object-name config setting.

=cut

# use modules
use warnings;
use strict;
use Mnet;
use Mnet::Model;
use Mnet::Silent;
use Data::Dumper;

# read config
my $cfg = &config({
    'main-version'  => '+++VERSION+++',
});

# read object arg
die "usage: $0 --object-name <object> [--db-name <db>] [--data-dir <dir>]\n"
    if not defined $cfg->{'object-name'};

# retrieve object info
my $info = &object_info({
    'object' => $cfg->{'object-name'},
});

# output object info
print Dumper $info;

# finished;
exit;



=head1 COPYRIGHT AND LICENSE

Copyright 2006, 2013-2014 Michael J. Menza Jr.
Refer to `perldoc Mnet` for more information.

=head1 SEE ALSO

Mnet, Mnet::Model

=cut

