#!/usr/bin/perl

=head1 NAME

Mnet::bin/Mnet-rrd-png - network automation script

=cut

# Copyright 2006, 2013-2014 Michael J. Menza Jr.
# Refer to `perldoc Mnet` for more information.

=head1 SYNOPSIS

Usage examples:

 Mnet-rrd-png \
    --data-dir /data/dir \
    --object-name localhost \
    --rrd cpu.val \
    --rrd-period short

=head1 DESCRIPTION

This script uses the Mnet::Model module to output the specified rrd
graph to standard output in png format.

The --data-dir, --object-name and --rrd command line arguments are
all required.

Refer to the Mnet::Model documentation alert_query function for a list
of valid inputs. Prefix each input with rrd on the command line, such
as rrd-width, rrd-height, etc.

=cut

# use modules
use warnings;
use strict;
use Mnet;
use Mnet::Model;
use Mnet::Silent;

# read config
my $cfg = &config({
    'main-version'  => '+++VERSION+++',
});

# read object arg
die "usage: $0 --data-dir <dir> --object-name <object> --rrd <file>\n"
    if not defined $cfg->{'data-dir'}
    or not defined $cfg->{'object-name'}
    or not defined $cfg->{'rrd'};

# move query config settings to input hash
my $input = {};
$input->{'object'} = $cfg->{'object-name'};
$input->{'rrd'} = $cfg->{'rrd'};
foreach my $key (keys %$cfg) {
    next if $key !~ /rrd-(\S+)/;
    $input->{$1} = $cfg->{$key};
}

# retrieve rrd png
my $png = &rrd_png($input);

# output rrd png, if defined
print $png if defined $png;

# finished;
exit;



=head1 COPYRIGHT AND LICENSE

Copyright 2006, 2013-2014 Michael J. Menza Jr.
Refer to `perldoc Mnet` for more information.

=head1 SEE ALSO

Mnet, Mnet::Model

=cut

