
=head1 NAME

Mnet

=head1 SYNOPSIS

The Mnet modules are for perl programmers who want to create network
automation, reporting, and monitoring scripts.

Here's some sample code showing typical usage:

    # use the logging module,
    use Mnet::Log qw(DEBUG INFO WARN FATAL);

    # use the cli option parsing module
    use Mnet::Opts::Cli;

    # use the test record/replay module
    use Mnet::Test;

    # define a cli option for this script
    Mnet::Opts::Cli::define({
        getopt   => "sample:s",
        help_tip => "string cli option",
    });

    # parse cli options
    my $cli = Mnet::Opts::Cli->new;

    # here's a bit of example code
    INFO("sample option set") if $cli->sample;

Refer to the TUTORIAL below to see what can be done with the above code, and
the SEE ALSO section of this perldoc for a complete list of Mnet perl modules.

=head1 TUTORIAL

#? finish tutorial
#   be sure to show use of all main modules, including Mnet::Batch

=cut

#? proofread and revise all perldoc and comments

#? create Mnet::Expect module
#   $self = Mnet::Expect->new
#   add -re '\r\N' progress bar handling
#       $match = $expect->match;
#       $match =~ /\N*\r(\N)/$1/;
#       $match .= $expect->after;
#       expect->set_accum($match);
#   how far does this module go?
#   how can we support weird menus and characters, etc
#   can we have multiple types of expect wrapper modules?
#   can we layer/enable/disable various capabilities?

#? create Mnet::Report module
#   $self = Mnet::Report->new($name, \%opts)
#   allow for --report output to database in addition to csv, etc
#   maybe use key = value storage in db, example key = 'dev int attrib'

#? create Mnet::Stash module
#   --stash=s, set to sqlite file, or directory to use $name+$key files
#   init creates sqlite table named mnet_stash_$name with $key rows
#   Mnet::Stash::init($name, \%opts) # cli --stash opt, maybe stash_age_max
#   \%stash = Mnet::Stash->new($name, $key)
#   end block saves/updates dbi data, unless read-only opt set
#   end block can remove stash entries older than stash_age_max

=head1 AUTHOR

The Mnet perl module has been created and is maintained by Mike Menza. Mike can
be reached via email at mmenza@cpan.org.

=head1 COPYRIGHT AND LICENSE

Copyright 2006, 2013-2018 Michael J. Menza Jr.

Mnet is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see http://www.gnu.org/licenses/

=head1 SEE ALSO

 Mnet::Batch
 Mnet::Dump
 Mnet::Log
 Mnet::Opts::Cli
 Mnet::Opts::Set::Debug
 Mnet::Opts::Set::Quiet
 Mnet::Opts::Set::Silent
 Mnet::Test

=cut

